In [ ]:
import warnings
warnings.simplefilter('ignore')

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv("Restaurant_Reviews.tsv", delimiter="\t",quoting=3)
df.head()

Review  Liked
0                           Wow... Loved this place.      1
1                                 Crust is not good.      0
2          Not tasty and the texture was just nasty.      0
3  Stopped by during the late May bank holiday of...      1
4  The selection on the menu was great and so wer...      1

In [ ]:
df.iloc[3]['Review']

'Stopped by during the late May bank holiday off Rick Steve recommendation and loved it.'

In [ ]:
df.shape

(1000, 2)

In [ ]:
df['Liked'].unique()

array([1, 0], dtype=int64)

In [ ]:
df['Liked'].value_counts()

1    500
0    500
Name: Liked, dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Review  1000 non-null   object
 1   Liked   1000 non-null   int64 
dtypes: int64(1), object(1)
memory usage: 15.8+ KB


In [ ]:
def assing(like):
    if like == 1 :
        return "Positive"
    elif like == 0:
        return "Negative"

df['Sentiment']= df['Liked'].apply(assing)

In [ ]:
df.head()

Review  Liked Sentiment
0                           Wow... Loved this place.      1  Positive
1                                 Crust is not good.      0  Negative
2          Not tasty and the texture was just nasty.      0  Negative
3  Stopped by during the late May bank holiday of...      1  Positive
4  The selection on the menu was great and so wer...      1  Positive

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   Review     1000 non-null   object
 1   Liked      1000 non-null   int64 
 2   Sentiment  1000 non-null   object
dtypes: int64(1), object(2)
memory usage: 23.6+ KB


In [ ]:
df.drop('Sentiment',axis=1)

Review  Liked
0                             Wow... Loved this place.      1
1                                   Crust is not good.      0
2            Not tasty and the texture was just nasty.      0
3    Stopped by during the late May bank holiday of...      1
4    The selection on the menu was great and so wer...      1
..                                                 ...    ...
995  I think food should have flavor and texture an...      0
996                           Appetite instantly gone.      0
997  Overall I was not impressed and would not go b...      0
998  The whole experience was underwhelming, and I ...      0
999  Then, as if I hadn't wasted enough of my life ...      0

[1000 rows x 2 columns]

In [ ]:
df.head()

Review  Liked Sentiment
0                           Wow... Loved this place.      1  Positive
1                                 Crust is not good.      0  Negative
2          Not tasty and the texture was just nasty.      0  Negative
3  Stopped by during the late May bank holiday of...      1  Positive
4  The selection on the menu was great and so wer...      1  Positive

In [ ]:
df.drop('Sentiment',axis=1, inplace=True)

In [ ]:
df.head()

Review  Liked
0                           Wow... Loved this place.      1
1                                 Crust is not good.      0
2          Not tasty and the texture was just nasty.      0
3  Stopped by during the late May bank holiday of...      1
4  The selection on the menu was great and so wer...      1

In [ ]:
df.isna().sum()

Review    0
Liked     0
dtype: int64

In [ ]:
# Assume that there were 2 na values in the df.
# In that case, we would have dropped them.

df.dropna(inplace=True)
df.head()

Review  Liked
0                           Wow... Loved this place.      1
1                                 Crust is not good.      0
2          Not tasty and the texture was just nasty.      0
3  Stopped by during the late May bank holiday of...      1
4  The selection on the menu was great and so wer...      1

In [ ]:
df['Review'][0]

'Wow... Loved this place.'

In [ ]:
#Importing Regular Expression library
import re

#Subsitituting special characters with spaces

review = re.sub( '[^a-zA-Z]' , ' ', df['Review'][0] )
review

'Wow    Loved this place '

In [ ]:
review

'Wow    Loved this place '

In [ ]:
#Lowering the case

review = review.lower()

In [ ]:
review

'wow    loved this place '

In [ ]:
#Splitting the sentence into individual words

review = review.split()
review

['wow', 'loved', 'this', 'place']

In [ ]:
import nltk # Natural Language Tool Kit
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ingle\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
from nltk.corpus import stopwords

In [ ]:
len(stopwords.words('english'))

179

In [ ]:
review

['wow', 'loved', 'this', 'place']

In [ ]:
#Removing stop words
review1 = [ word for word in review if not word in set(stopwords.words('english')) ]
review1

['wow', 'loved', 'place']

In [ ]:
# Retrieving original words

from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
review1 = [ ps.stem(word) for word in review1 ]
review1

['wow', 'love', 'place']

In [ ]:
review2 = ' '.join(review1)
review2

'wow love place'

In [ ]:
#Creating corpus using Count vectoriser
corpus1 = []
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=3)
print(review2)
corpus1.append(review2)
print(corpus1)
X = cv.fit_transform(corpus1)

wow love place
['wow love place']


In [ ]:
X

<1x3 sparse matrix of type '<class 'numpy.int64'>'
	with 3 stored elements in Compressed Sparse Row format>

In [ ]:
X.toarray()

array([[1, 1, 1]], dtype=int64)

In [ ]:
df.shape

(1000, 2)

In [ ]:
#Applying all above to whole dataframe

import re
import nltk
# nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
corpus = []
for i in range(0,1000):
    review = re.sub( '[^a-zA-Z]' , ' ' , df['Review'][i] )
    review = review.lower()
    review = review.split()
    ps = PorterStemmer()
    review = [ ps.stem(word) for word in review if not word in set(stopwords.words('english')) ]
    review = ' '.join(review)
    print(review)
    corpus.append(review)

wow love place
crust good
tasti textur nasti
stop late may bank holiday rick steve recommend love
select menu great price
get angri want damn pho
honeslti tast fresh
potato like rubber could tell made ahead time kept warmer
fri great
great touch
servic prompt
would go back
cashier care ever say still end wayyy overpr
tri cape cod ravoli chicken cranberri mmmm
disgust pretti sure human hair
shock sign indic cash
highli recommend
waitress littl slow servic
place worth time let alon vega
like
burritto blah
food amaz
servic also cute
could care less interior beauti
perform
right red velvet cake ohhh stuff good
never brought salad ask
hole wall great mexican street taco friendli staff
took hour get food tabl restaur food luke warm sever run around like total overwhelm
worst salmon sashimi
also combo like burger fri beer decent deal
like final blow
found place accid could happier
seem like good quick place grab bite familiar pub food favor look elsewher
overal like place lot
redeem qualiti r

overal think would take parent place made similar complaint silent felt
pizza good peanut sauc tasti
tabl servic pretti fast
fantast servic
well would given godfath zero star possibl
know make
tough short flavor
hope place stick around
bar vega ever recal charg tap water
restaur atmospher exquisit
good servic clean inexpens boot
seafood fresh gener portion
plu buck
servic par either
thu far visit twice food absolut delici time
good year ago
self proclaim coffe cafe wildli disappoint
veggitarian platter world
cant go wrong food
beat
stop place madison ironman friendli kind staff
chef friendli good job
better dedic boba tea spot even jenni pho
like patio servic outstand
goat taco skimp meat wow flavor
think
mac salad pretti bland get
went bachi burger friend recommend disappoint
servic stink
wait wait
place qualiti sushi qualiti restaur
would definit recommend wing well pizza
great pizza salad
thing went wrong burn saganaki
wait hour breakfast could done time better home
place amaz
hate 

everyth perfect night
food good typic bar food
drive get
first glanc love bakeri cafe nice ambianc clean friendli staff
anyway think go back
point finger item menu order disappoint
oh thing beauti restaur
gone go
greasi unhealthi meal
first time might last
burger amaz
similarli deliveri man say word apolog food minut late
way expens
sure order dessert even need pack go tiramisu cannoli die
first time wait next
bartend also nice
everyth good tasti
place two thumb way
best place vega breakfast check sat sun
love authent mexican food want whole bunch interest yet delici meat choos need tri place
terribl manag
excel new restaur experienc frenchman
zero star would give zero star
great steak great side great wine amaz dessert
worst martini ever
steak shrimp opinion best entre gc
opportun today sampl amaz pizza
wait thirti minut seat although vacant tabl folk wait
yellowtail carpaccio melt mouth fresh
tri go back even empti
go eat potato found stranger hair
spici enough perfect actual
last ni

pay hot dog fri look like came kid meal wienerschnitzel idea good meal
classic main lobster roll fantast
brother law work mall ate day guess sick night
good go review place twice herea tribut place tribut event held last night
chip salsa realli good salsa fresh
place great
mediocr food
get insid impress place
super pissd
servic super friendli
sad littl veget overcook
place nice surpris
golden crispi delici
high hope place sinc burger cook charcoal grill unfortun tast fell flat way flat
could eat bruschetta day devin
singl employe came see ok even need water refil final serv us food
lastli mozzarella stick best thing order
first time ever came amaz experi still tell peopl awesom duck
server neglig need made us feel unwelcom would suggest place
servic terribl though
place overpr consist boba realli overpr
pack
love place
say dessert yummi
food terribl
season fruit fresh white peach pure
kept get wors wors offici done
place honestli blown
definit would eat
wast money
love put food nice pl

In [ ]:
corpus

['wow love place',
 'crust good',
 'tasti textur nasti',
 'stop late may bank holiday rick steve recommend love',
 'select menu great price',
 'get angri want damn pho',
 'honeslti tast fresh',
 'potato like rubber could tell made ahead time kept warmer',
 'fri great',
 'great touch',
 'servic prompt',
 'would go back',
 'cashier care ever say still end wayyy overpr',
 'tri cape cod ravoli chicken cranberri mmmm',
 'disgust pretti sure human hair',
 'shock sign indic cash',
 'highli recommend',
 'waitress littl slow servic',
 'place worth time let alon vega',
 'like',
 'burritto blah',
 'food amaz',
 'servic also cute',
 'could care less interior beauti',
 'perform',
 'right red velvet cake ohhh stuff good',
 'never brought salad ask',
 'hole wall great mexican street taco friendli staff',
 'took hour get food tabl restaur food luke warm sever run around like total overwhelm',
 'worst salmon sashimi',
 'also combo like burger fri beer decent deal',
 'like final blow',
 'found place acc

In [ ]:
corpus_df = pd.DataFrame(corpus)

In [ ]:
corpus_df.head()

0
0                                     wow love place
1                                         crust good
2                                 tasti textur nasti
3  stop late may bank holiday rick steve recommen...
4                            select menu great price

In [ ]:
corpus_df.columns = ['corpus']

In [ ]:
corpus_df.head()

corpus
0                                     wow love place
1                                         crust good
2                                 tasti textur nasti
3  stop late may bank holiday rick steve recommen...
4                            select menu great price

In [ ]:
corpus_df.to_csv('corpus_dataset.csv')

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=1500)

In [ ]:
X = cv.fit_transform(corpus).toarray()

In [ ]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [ ]:
df.head()

Review  Liked
0                           Wow... Loved this place.      1
1                                 Crust is not good.      0
2          Not tasty and the texture was just nasty.      0
3  Stopped by during the late May bank holiday of...      1
4  The selection on the menu was great and so wer...      1

In [ ]:
X[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [ ]:
len(X[0])

1500

In [ ]:
X.shape

(1000, 1500)

In [ ]:
cv.get_feature_names()

['absolut',
 'absolutley',
 'accid',
 'accommod',
 'accomod',
 'accordingli',
 'account',
 'ach',
 'acknowledg',
 'across',
 'actual',
 'ad',
 'afford',
 'afternoon',
 'ago',
 'ahead',
 'airlin',
 'airport',
 'ala',
 'albondiga',
 'allergi',
 'almond',
 'almost',
 'alon',
 'also',
 'although',
 'alway',
 'amaz',
 'ambianc',
 'ambienc',
 'amount',
 'ampl',
 'andddd',
 'angri',
 'annoy',
 'anoth',
 'anticip',
 'anymor',
 'anyon',
 'anyth',
 'anytim',
 'anyway',
 'apart',
 'apolog',
 'app',
 'appal',
 'appar',
 'appeal',
 'appet',
 'appetit',
 'appl',
 'approv',
 'area',
 'arepa',
 'aria',
 'around',
 'array',
 'arriv',
 'articl',
 'ask',
 'assur',
 'ate',
 'atmospher',
 'atroci',
 'attach',
 'attack',
 'attent',
 'attitud',
 'auju',
 'authent',
 'averag',
 'avocado',
 'avoid',
 'aw',
 'away',
 'awesom',
 'awkward',
 'awkwardli',
 'ayc',
 'az',
 'baba',
 'babi',
 'bachi',
 'back',
 'bacon',
 'bad',
 'bagel',
 'bakeri',
 'baklava',
 'ball',
 'bamboo',
 'banana',
 'bank',
 'bar',
 'bare',
 

In [ ]:
y = df.iloc[:,1].values

In [ ]:
y.shape

(1000,)

In [ ]:
#Spilitting dataset into Train and Test datasets

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=0)

In [ ]:
#Applying Naive Bayes algorithm
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()
clf.fit(X_train, y_train)

GaussianNB()

In [ ]:
y_pred = clf.predict(X_test)

In [ ]:
y_pred

array([1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 1], dtype=int64)

In [ ]:
y_test

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 1], dtype=int64)

In [ ]:
list(zip(y_pred,y_test))

[(1, 0),
 (1, 0),
 (1, 0),
 (0, 0),
 (0, 0),
 (1, 0),
 (1, 1),
 (1, 0),
 (1, 0),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 0),
 (1, 1),
 (1, 1),
 (1, 1),
 (0, 0),
 (0, 0),
 (0, 0),
 (1, 1),
 (0, 0),
 (0, 1),
 (1, 1),
 (1, 0),
 (1, 0),
 (0, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (0, 0),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (0, 0),
 (1, 0),
 (0, 0),
 (1, 0),
 (1, 1),
 (1, 1),
 (1, 0),
 (1, 1),
 (0, 0),
 (0, 0),
 (0, 0),
 (1, 0),
 (1, 0),
 (0, 0),
 (0, 0),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 0),
 (0, 0),
 (1, 1),
 (1, 1),
 (0, 0),
 (1, 1),
 (1, 0),
 (0, 0),
 (1, 0),
 (1, 0),
 (1, 1),
 (0, 0),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 0),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (0, 0),
 (1, 0),
 (1, 1),
 (0, 1),
 (0, 0),
 (1, 1),
 (0, 0),
 (1, 1),
 (1, 1),
 (0, 0),
 (1, 1),
 (1, 1),
 (1, 0),
 (0, 0),
 (1, 1),
 (1, 0),
 (0, 0),
 (1, 1),
 (0, 0),
 (0, 0),
 (1, 0),
 (1, 1),
 (1, 0),
 (1, 1),
 (1, 1),
 (1, 0),
 (0, 1),
 (1, 1),
 (1, 1),
 (1, 0),
 (0, 1),
 (1, 0),
 (1, 1),
 (1, 1),
 (0, 0),
 (0, 1),
 (0, 1),
 

In [ ]:
cmp = pd.DataFrame({
    'Predicted' : y_pred,
    'Actual' : y_test
})
cmp

Predicted  Actual
0            1       0
1            1       0
2            1       0
3            0       0
4            0       0
..         ...     ...
195          0       0
196          1       1
197          1       1
198          1       0
199          1       1

[200 rows x 2 columns]

In [ ]:
#Incorrect Predictions
(cmp['Predicted'] != cmp['Actual']).sum()

54

In [ ]:
#Correct Predictions
(cmp['Predicted'] == cmp['Actual']).sum()

146

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [ ]:
confusion_matrix(y_test, y_pred)

array([[55, 42],
       [12, 91]], dtype=int64)

In [ ]:
accuracy_score(y_test, y_pred)

0.73

In [ ]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.82      0.57      0.67        97
           1       0.68      0.88      0.77       103

    accuracy                           0.73       200
   macro avg       0.75      0.73      0.72       200
weighted avg       0.75      0.73      0.72       200



In [ ]:
clf

GaussianNB()

In [ ]:
#Saving model into file
import joblib
joblib.dump(clf,r"model.pkl")

['model.pkl']

In [ ]:
#Testing model with unseen data
Review = 'nice service'
input_data = [Review]

input_data = cv.transform(input_data).toarray()
input_data

array([[0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [ ]:
len(input_data[0])

1500

In [ ]:
input_pred = clf.predict(input_data)
input_pred

array([1], dtype=int64)

In [ ]:
input_pred[0]

1

In [ ]:
if input_pred[0]==1:
    print("Review is Positive")
else:
    print("Review is Negative")

Review is Positive


In [ ]:
Review = 'nice service'
input_data = [Review]

input_data = cv.transform(input_data).toarray()
input_pred = clf.predict(input_data)
if input_pred[0]==1:
    print("Review is Positive")
else:
    print("Review is Negative")

Review is Positive


In [ ]:
#Testing model with unseen data
Review = 'long waiting time'
input_data = [Review]

input_data = cv.transform(input_data).toarray()
input_pred = clf.predict(input_data)
if input_pred[0]==1:
    print("Review is Positive")
else:
    print("Review is Negative")

Review is Negative


# Happy Learning